name: 'test'

on:
    push:
    pull_request:
    schedule:
      - cron: '0 15 * * *'

env:
  CI: true
  PY_COLORS: "1"
  SIM: ghdl
  TOPLEVEL_LANG: vhdl

jobs:


  lin:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: ghdl/setup-ghdl-ci@master
      with:
        backend: llvm

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: pip install --no-build-isolation .

    - run: make SIM=ghdl TOPLEVEL_LANG=vhdl


  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { lang: verilog, sim: verilator, pkg: verilator }
          - { lang: verilog, sim: icarus, pkg: iverilog }
          - { lang: vhdl, sim: ghdl, pkg: ghdl-llvm }
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-pytest
            mingw-w64-x86_64-python-wheel
            mingw-w64-x86_64-${{ matrix.pkg }}

    - uses: actions/checkout@v2

    - run: pip install --no-build-isolation .

    - run: make SIM=${{ matrix.sim }} TOPLEVEL_LANG=${{ matrix.lang }}


  win-ghdl:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
            git
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-pytest
            mingw-w64-x86_64-python-wheel

    - uses: actions/checkout@v2

    - uses: ghdl/setup-ghdl-ci@master
      with:
        backend: llvm

    - run: pip install --no-build-isolation .

    - run: make SIM=ghdl TOPLEVEL_LANG=vhdl


  win-docs:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
            mingw-w64-x86_64-doxygen
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-python-cairo
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-sphinx

    - uses: actions/checkout@v2

    - run: python -m pip install --progress-bar off tox

    - run: tox -e docs
