name: 'vunit'

on:
  push:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ghdl/setup-ghdl-ci@master
      with:
        backend: llvm
    - run: ghdl --version
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --progress-bar off tox vunit_hdl
    - name: Test dff
      run: |
        python setup.py install
        cd examples/dff/tests
        TOPLEVEL_LANG=vhdl SIM=ghdl make
    - name: Run VUnit
      run: |
        cd examples/dff/tests
        python run.py -v
